### ISSUE TITLE
notebook-operators failing bundle integration tests track/1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/notebook-operators#265]
# Description

Discovered during running on pull request workflows when not related image retrieval script was checked in.
Bundle integration tests are failing `tox -e integration -- --model kubeflow` in the workflow.
This PR has the logs/traces for failing tests https://github.com/canonical/notebook-operators/pull/264

Need to review and address failing ibindle ntegration tests.

Tests are failing in GH runner:
```
____________________________ test_build_and_deploy _____________________________
Traceback (most recent call last):
  File "/home/runner/work/notebook-operators/notebook-operators/tests/test_charms.py", line 71, in test_build_and_deploy
    controller_charm = await ops_test.build_charm(CONTROLLER_PATH)
  File "/home/runner/work/notebook-operators/notebook-operators/.tox/integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 977, in build_charm
    raise RuntimeError(
RuntimeError: Failed to build charm charms/jupyter-controller:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
Packing the charm
Packing the charm.
Building charm in '/root'
Running step PULL for part 'charm'
Running step BUILD for part 'charm'
Parts processing error: Failed to run the build script for part 'charm'.
Failed to build charm for bases index '0'.
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230723-190252.423901.log'
```
Publishing also fails in GH runner:
```
Run canonical/charming-actions/upload-charm@2.2.2
  with:
    credentials: ***
    github-token: ***
    charm-path: ./charms/jupyter-controller
    channel: 1.7/edge/kf-3878-feat-images-script
    tag-prefix: jupyter-controller
    destructive-mode: true
    charmcraft-channel: latest/stable
    upload-image: true
/usr/bin/sudo snap install charmcraft --classic --channel latest/stable
charmcraft [2](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:2).[3](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:3).0 from Canonical** installed
/usr/bin/sudo charmcraft pack --quiet --destructive-mode
Parts processing error: Failed to run the build script for part 'charm'.
Full execution log: '/root/.local/state/charmcraft/log/charmcraft-20230723-185726.3[4](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:4)7362.log'
Error: The process '/usr/bin/sudo' failed with exit code 1
Error: Error: The process '/usr/bin/sudo' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:3763:2[5](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:5))
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:374[6](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:6):18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/2.2.2/dist/upload-charm/index.js:3640:2[7](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:7))
    at ChildProcess.emit (node:events:527:2[8](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:8))
    at maybeClose (node:internal/child_process:10[9](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:9)2:[16](https://github.com/canonical/notebook-operators/actions/runs/5638096305/job/15271879695?pr=270#step:5:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
/usr/bin/sudo test -d /root/snap/charmcraft/common/cache/charmcraft/log
No charmcraft logs generated, skipping artifact upload.
```

Admission webhook is failing to install from latest/edge. This is due to the fact that it was re-written and requires trust now.
```
admission-webhook/0*     error     idle        10.1.86.17         hook failed: "install"
```
# Solution
Problem description and possible solutions are in https://github.com/canonical/bundle-kubeflow/issues/648

**Comment by i-chvets** [comment]
Refer to this PR for work being done on debugging the issiein GH runners:
https://github.com/canonical/notebook-operators/pull/264

**Comment by i-chvets** [comment]
If requirements are to be updated, new packages will be brought it. This will cause might cause some issues.

**Comment by i-chvets** [comment]
More details on problem description and solutions in: https://github.com/canonical/bundle-kubeflow/issues/648

**Comment by i-chvets** [comment]
Fix is merged. Closing.
